apiVersion: v1
kind: Service
metadata:
  name: trueview-zookeeper
  namespace: trueview
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/part-of: trueview-stack
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: peer
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
  selector:
    app.kubernetes.io/name: trueview-zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: trueview-zookeeper-headless
  namespace: trueview
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/part-of: trueview-stack
spec:
  clusterIP: None
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  selector:
    app.kubernetes.io/name: trueview-zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trueview-zookeeper
  namespace: trueview
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/part-of: trueview-stack
spec:
  serviceName: trueview-zookeeper-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trueview-zookeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trueview-zookeeper
        app.kubernetes.io/component: zookeeper
        app.kubernetes.io/part-of: trueview-stack
    spec:
      containers:
        - name: zookeeper
          image: signoz/zookeeper:3.7.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 2181
            - name: peer
              containerPort: 2888
            - name: election
              containerPort: 3888
            - name: metrics
              containerPort: 9141
          env:
            - name: ZOO_SERVER_ID
              value: "1"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOO_AUTOPURGE_INTERVAL
              value: "1"
            - name: ZOO_ENABLE_PROMETHEUS_METRICS
              value: "yes"
            - name: ZOO_PROMETHEUS_METRICS_PORT_NUMBER
              value: "9141"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -s -m 2 http://localhost:8080/commands/ruok | grep imok"
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl -s -m 2 http://localhost:8080/commands/ruok | grep imok"
            initialDelaySeconds: 10
            periodSeconds: 15
          volumeMounts:
            - name: data
              mountPath: /bitnami/zookeeper
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: trueview-zookeeper-data
